#
# Use this configuration file to control what RobotPy packages are installed on your RoboRIO
# NOTE: Extra module `limelightlib-python` cannot be added to toml file (for some reason). Read wiki on installing:
#   limelightlib-python
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.3.2.1"

# Which extra RobotPy components should be installed -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    "navx",
    "rev",
    "pathplannerlib",
]

# Other pip packages to install
requires = [ "numpy", "phoenix6", "wheel" ]